name: Log Github Action run times

on:
  workflow_dispatch:
  schedule:
    - cron: "*/7 * * * *"
      timezone: "Asia/Kolkata"

permissions: 
  contents: write

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Configure git for commits
        run: |-
          git config --global user.name "Automated Monkey"
          git config --global user.email "actions@users.noreply.github.com"

      - name: Log execution time
        run: |-
          timestamp=$(date -u)
          echo "Executed: ${timestamp} by ${{github.run_id}}" >> actions-log.txt

      - name: Commit changes
        run: |-
          git add .
          timestamp=$(date -u)
          git commit -m "Update latest execution run: ${timestamp}"
          git push
